Feat/add-ai-func-management-cookbook
growilabs/growi-docs pull request #534
Opened 2024-10-31 09:07 UTC by TatsuyaIse

https://redmine.weseek.co.jp/issues/156642

2024-10-31 09:09 UTC, TatsuyaIse commented
![image](https://github.com/user-attachments/assets/34361103-3dce-4207-8b3d-7401fa658d58)

2024-11-01 05:28 UTC, TatsuyaIse commented
![image](https://github.com/user-attachments/assets/49b4eb29-1f01-446c-8bd9-01ed8c8df6ed)

2024-11-01 05:43 UTC, TatsuyaIse commented
GROWI Docs の表示
![image](https://github.com/user-attachments/assets/cba6e9f3-32fa-4564-a074-217b1a761970)

2024-11-01 08:48 UTC, miya requested changes

2024-11-01 08:48 UTC, miya commented on docs/ja/admin-guide/management-cookbook/setup-ai.md
> +  - AI 連携機能の設定は環境変数による指定のみ可能です。
これは実装予定は無いので消して良いと思います

2024-11-01 08:48 UTC, miya commented on docs/ja/admin-guide/management-cookbook/setup-ai.md
> +  - `OPENAI_API_KEY` に OpenAI サービスで取得した API キーを指定
ここにも記載お願いします
https://docs.growi.org/ja/admin-guide/admin-cookbook/env-vars.html

2024-11-01 08:48 UTC, miya commented on docs/ja/admin-guide/management-cookbook/setup-ai.md
> +- AI 連携機能が有効な場合、パブリックなページの作成・更新時にページの本文ほか機械学習に必要なメタデータを `Vector Store` へアップロードしますが、既存のページについてはページを更新しない限り学習対象となりません。
> 既存のページについてはページを更新しない限り

ページの作成・更新・複製 に修正お願いします

2024-11-01 08:48 UTC, miya commented on docs/ja/admin-guide/management-cookbook/setup-ai.md
> +  <img :src="$withBase('/assets/images/ja/setup-ai_2.png')" alt="setup-ai_2">
GROWI AI の中の「ナレッジアシスタント」という機能のセクションだとわかるように組み替えをお願いします

2024-11-05 04:00 UTC, TatsuyaIse commented on docs/ja/admin-guide/management-cookbook/setup-ai.md
> +- AI 連携機能が有効な場合、パブリックなページの作成・更新時にページの本文ほか機械学習に必要なメタデータを `Vector Store` へアップロードしますが、既存のページについてはページを更新しない限り学習対象となりません。
ちょっと確認したく、  
ページの作成・更新・複製 (作成と同義だと思っていた) 時に、該当ページのみのデータが Vector Store にアップロードされる。  
という認識だったんだけれど、新規ページ作成時の親ページなど、関連がある？ページだったり、複製時の複製元のページだったりも
 Vector Store にアップロードされたりする？？  
修正の方向性を誤らないための確認です 🙏

2024-11-05 04:09 UTC, TatsuyaIse commented on docs/ja/admin-guide/management-cookbook/setup-ai.md
> +  <img :src="$withBase('/assets/images/ja/setup-ai_2.png')" alt="setup-ai_2">
自分の中で、ゴールがちょっとあいまいだったので確認  

- Slack 連携みたいな感じで、ページまるごと階層分けをした方がいいのか、  
- 一旦は、このページの中で見出しの階層をつけるなどで組み換えをすればいいのか、  

だと、どっちだろう？？  
もしくは、それ以外で、こういう形！という想定があれば、簡単に教えてほしいかもです 🙏

2024-11-05 04:33 UTC, miya commented on docs/ja/admin-guide/management-cookbook/setup-ai.md
> +- AI 連携機能が有効な場合、パブリックなページの作成・更新時にページの本文ほか機械学習に必要なメタデータを `Vector Store` へアップロードしますが、既存のページについてはページを更新しない限り学習対象となりません。
>  ページの作成・更新・複製 (作成と同義だと思っていた) 時に、該当ページのみのデータが Vector Store にアップロードされる。

この認識であっています。

> という認識だったんだけれど、新規ページ作成時の親ページなど、関連がある？ページだったり、複製時の複製元のページだったりも
> Vector

アクションが起こったページ (作成・更新・複製) のみが VectorStore へのアップロードの対象になります。

2024-11-05 04:33 UTC, miya commented on docs/ja/admin-guide/management-cookbook/setup-ai.md
> +  <img :src="$withBase('/assets/images/ja/setup-ai_2.png')" alt="setup-ai_2">
> 一旦は、このページの中で見出しの階層をつけるなどで組み換えをすればいいのか、

どちらかといえばこちらかなと思っています。「VectroStore のリビルド」がなんのために必要なのかというのを具体的に書いて欲しかったです。


> 「Vector Store のリビルド」を行うことで、すべてのパブリックなページを `Vector Store` に取り込ませることができます。

例えばこれはパブリックページを Vector Store に取り込ませた結果、何ができるようになるのかがわかりにくいと感じました。

2024-11-07 06:28 UTC, miya requested changes

2024-11-07 06:28 UTC, miya commented on docs/en/admin-guide/admin-cookbook/env-vars.md
> +|  | `azure-openai` | Use "Azure OpenAI" |
azure-openai は未対応なのでコメントアウトしていただけると助かります。対応予定はあります。

2024-11-08 09:18 UTC, miya commented on docs/ja/admin-guide/management-cookbook/setup-ai.md
> +</ContextualBlock>
これは AI 機能共通だと思うので「ナレッジアシスタント機能」のセクションより上にほしいです

2024-11-11 04:24 UTC, TatsuyaIse commented on docs/ja/admin-guide/management-cookbook/setup-ai.md
> +</ContextualBlock>
見出しの上に移動しました。  
一部見出しの階層も変更

2024-11-12 03:07 UTC, merged