prepare knowledge assistant feature guide page
growilabs/growi-docs pull request #535
Opened 2024-11-01 06:16 UTC by TatsuyaIse

https://redmine.weseek.co.jp/issues/156641

2024-11-01 08:52 UTC, TatsuyaIse commented
![image](https://github.com/user-attachments/assets/2cc7d434-e31d-4fbe-856d-9e6aeb53f1f9)

2024-11-07 06:50 UTC, miya requested changes

2024-11-07 06:50 UTC, miya commented on docs/ja/guide/features/ai-knowledge-assistant.md
VectorStore の rebuild 方法が書いてあるページへの導線が欲しいですね！

2024-11-08 06:03 UTC, TatsuyaIse commented on docs/ja/guide/features/ai-knowledge-assistant.md
導線用意しました！

2024-11-08 08:50 UTC, merged